version: "3.9"

services:
  fake-api:
    build: .
    container_name: santander_dio_fake_api
    ports:
      - "8000:8000"
    volumes:
      - ./data.json:/app/data.json
    restart: unless-stopped
